// Compare-page data
window.COMPARE_DATA = {
  ekimetrics: {
    them: 'Ekimetrics',
    eyebrow: 'Compare',
    title: 'Jurnii MMM vs Ekimetrics',
    lede: 'Ekimetrics is a credible, established MMM consultancy. Here\'s where the model fits — and where the iGaming-specific gap opens.',
    rows: [
      { row: 'Built for iGaming as a vertical', us: 'Yes — every modelling choice is iGaming-first', them: 'No — sector-agnostic methodology', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Bonus mechanics as model inputs', us: 'First-class structured input', them: 'Aggregated into "promotional spend"', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Sporting calendar awareness', us: 'Built in — Cheltenham, World Cup, NFL, etc.', them: 'Treated as outliers / event flags', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Regulatory shock handling', us: 'Modelled as exogenous shocks', them: 'Bespoke — depends on engagement', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Competitor pressure variable', us: 'Direct integration with Jurnii 360', them: 'Not part of the standard model', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Cross-sector benchmarking', us: 'Not offered', them: 'Strong — multi-sector pedigree', usCls: 'cmp-no', themCls: 'cmp-yes' },
      { row: 'Time to first model', us: '4–6 weeks', them: '10–16 weeks', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Quarterly refresh', us: 'Standard', them: 'Per engagement, varies', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Brand-equity modelling', us: 'Limited (roadmap)', them: 'Strong, longstanding capability', usCls: 'cmp-partial', themCls: 'cmp-yes' },
    ],
    body: [
      { h: 'When Ekimetrics is the right call', p: 'If iGaming is one of several verticals in your group, and you want a single methodology across everything, Ekimetrics will give you that. Their cross-sector benchmarking is genuinely valuable, and their brand-equity work is better than ours.' },
      { h: 'When Jurnii is the right call', p: 'If iGaming is your business, and the questions you\'re asking are: "Is this reload offer driving incremental revenue?" "How does Cheltenham change the channel mix?" "Is paid social saturated?" — these are questions Jurnii MMM was built to answer with the right variables in the model.' },
    ],
  },
  nielsen: {
    them: 'Nielsen MMM',
    eyebrow: 'Compare',
    title: 'Jurnii MMM vs Nielsen MMM',
    lede: 'Nielsen is the FMCG gold standard. The variables that move iGaming aren\'t in their core model.',
    rows: [
      { row: 'Built for iGaming as a vertical', us: 'Yes', them: 'No — FMCG-first methodology', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Bonus mechanics as model inputs', us: 'First-class structured input', them: 'Not standard', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Brand-tracking panel data', us: 'Not offered', them: 'Industry-leading panel', usCls: 'cmp-no', themCls: 'cmp-yes' },
      { row: 'TV at-scale attribution', us: 'Strong (UK, EU)', them: 'Strong globally', usCls: 'cmp-yes', themCls: 'cmp-yes' },
      { row: 'Competitor pressure variable', us: 'Direct integration with Jurnii 360', them: 'Not in standard model', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Sporting calendar decomposition', us: 'Built in', them: 'Bespoke', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Time to first model', us: '4–6 weeks', them: '12–20 weeks', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'iGaming-native consultancy', us: 'Yes', them: 'No', usCls: 'cmp-yes', themCls: 'cmp-no' },
    ],
    body: [
      { h: 'Where Nielsen still wins', p: 'Long-term brand-tracking and panel data. Their panel is genuinely unique. If brand-equity modelling is a primary use case, Nielsen has the better data set.' },
      { h: 'Why iGaming operators are switching', p: 'Operators tell us the same thing: Nielsen models look defensible until you ask them to explain a Cheltenham week, and then the residuals double. The structural mismatch shows up in coefficients you can\'t defend in a board meeting.' },
    ],
  },
  'ux-agencies': {
    them: 'Traditional UX agencies',
    eyebrow: 'Compare',
    title: 'Jurnii UX vs traditional UX agencies',
    lede: 'Agencies do qualitative work brilliantly. They don\'t scale, and they don\'t carry NGR weight.',
    rows: [
      { row: 'Quarterly re-scoring', us: 'Standard', them: 'Rarely', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Same-rubric peer benchmarking', us: '5 peers, every quarter', them: 'Bespoke per project', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Cross-platform coverage', us: 'iOS, Android, mobile, desktop — all 4', them: 'Sample-based per project', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'NGR-weighted prioritisation', us: 'Built in', them: 'Inconsistent', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Generative research', us: 'Not offered', them: 'Strong', usCls: 'cmp-no', themCls: 'cmp-yes' },
      { row: 'Hero redesigns', us: 'Not offered', them: 'Strong', usCls: 'cmp-no', themCls: 'cmp-yes' },
      { row: 'Time to first audit', us: '~12 days', them: '8–12 weeks', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Annual cost (1 op + 5 peers)', us: 'From £80k', them: '£200k+ for equivalent depth', usCls: 'cmp-yes', themCls: 'cmp-no' },
    ],
    body: [
      { h: 'You probably need both', p: 'Agencies are still the right partner for generative research and hero redesigns. Jurnii UX replaces the part of the agency engagement that should be a system, not a project — quarterly structured benchmarking against a peer set.' },
      { h: 'What stops working at scale', p: 'A typical agency UX audit takes 8–12 weeks. By the time it lands, two of the five "top friction points" have already been addressed — and the report is stale. That\'s the gap Jurnii UX fills.' },
    ],
  },
  'manual-tracking': {
    them: 'In-house manual tracking',
    eyebrow: 'Compare',
    title: 'Jurnii 360 vs in-house manual tracking',
    lede: 'Two analysts, three spreadsheets, and a quarterly report. We costed it. The number is bigger than you think.',
    rows: [
      { row: 'Daily, structured capture', us: 'Yes — 20+ brands daily', them: 'Weekly at best, partial coverage', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Real-time change alerts', us: 'Slack / email / API', them: 'On Monday, in a deck', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Historical database', us: 'Multi-year, structured', them: 'Folder of screenshots', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'API / warehouse integration', us: 'REST API, Snowflake, BigQuery, Databricks', them: 'Spreadsheet exports', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Promotion richness scoring', us: 'Composite index, normalised across mechanics', them: 'Headline value comparison', usCls: 'cmp-yes', themCls: 'cmp-partial' },
      { row: 'Loaded annual cost', us: 'From £53.7k/yr', them: '£150k–£260k/yr (2 analysts + tooling + manager)', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Coverage scaling', us: 'Linear in price', them: 'Headcount-bounded', usCls: 'cmp-yes', themCls: 'cmp-no' },
      { row: 'Holiday / coverage risk', us: 'None', them: 'Real and recurring', usCls: 'cmp-yes', themCls: 'cmp-no' },
    ],
    body: [
      { h: 'The real cost of in-house', p: 'Two analysts at £55k loaded — £110k. Tooling and ad-hoc subscriptions — £20k. Manager time at 15% — £18k. Total: ~£150k–£180k for a partial, weekly view of a 5–8 brand competitor set. For 20 brands daily, you triple it.' },
      { h: 'What you actually want', p: 'Daily structured capture. Change alerts. A historical database. An API into your warehouse. Not a spreadsheet. We didn\'t invent a category — we productised what the smart operator was building anyway.' },
    ],
  },
};
