// ============================================================
// Use Cases — content data. Every leaf page + category page reads
// from here, so copy edits live in one place. Structure/layout
// lives in the template (use-case-page.jsx / use-case-archive.jsx).
// ============================================================

// Category metadata + ordered child slugs.
window.USE_CASE_CATS = {
  roles: {
    key: 'roles',
    label: 'Roles',
    icon: 'user-round',
    href: '/use-cases/roles',
    tagline: 'Executive personas and yield leaders.',
    lede: 'Built around the executives accountable for growth, margin, and operational velocity — each with the intelligence their remit demands.',
    children: ['cmo', 'coo', 'cco'],
  },
  'company-sizes': {
    key: 'company-sizes',
    label: 'Company Size',
    icon: 'building-2',
    href: '/use-cases/company-sizes',
    tagline: 'From challenger brands to multi-brand groups.',
    lede: 'Sized exactly for where you are today — agile challengers, scaling mid-market operators, and global multi-brand conglomerates.',
    children: ['smb', 'midmarket', 'enterprise'],
  },
  departments: {
    key: 'departments',
    label: 'Departments',
    icon: 'network',
    href: '/use-cases/departments',
    tagline: 'Cross-functional teams on the commercial floor.',
    lede: 'The intelligence each function needs on Monday morning — marketing, commercial, and product working from one source of truth.',
    children: ['marketing', 'commercial', 'product'],
  },
  sectors: {
    key: 'sectors',
    label: 'Sectors',
    icon: 'layers',
    href: '/use-cases/sectors',
    tagline: 'Verticals Jurnii intelligence maps onto.',
    lede: 'Native to digital gaming, and equally at home benchmarking conversion journeys across eCommerce and FinTech.',
    children: ['igaming', 'ecommerce', 'fintech'],
  },
};

// Shared blocks used by every leaf page (authored once).
window.USE_CASE_SHARED = {
  challengeSharedPara: 'When betting portals share the same suppliers, customer experience is the only durable barrier to player defection. Failing to benchmark your flow speed and copywriting clarity against competitor movements leaves your team fighting fires reactively.',
  solutionHeading: 'How Jurnii Solves This',
  solutionIcon: 'shield-check',
  implication: 'Friction in onboarding and mismatched promotion structures dilutes Net Gaming Revenue (<b>NGR</b>) and increases Customer Acquisition Cost (<b>CAC</b>) by up to <b>35%</b>.',
  benchmark: {
    heading: 'How Jurnii Outpaces the Market',
    lede: 'A side-by-side comparison of automated intelligence versus traditional retrospective manual setups.',
    cols: ['Jurnii Intelligence', 'Legacy Analytics', 'Manual Agencies'],
    rows: [
      { feat: 'Audit Frequency', jurnii: 'Continuous Real-Time', legacy: 'Ad-Hoc / Event Triggered', manual: 'Monthly / Retrospective' },
      { feat: 'Attribution Logic', jurnii: 'Cortex Causal Models', legacy: 'First-Click / Last-Click Errors', manual: 'Subjective / Gut Feel' },
      { feat: 'Data Structure', jurnii: 'Normalized Promo Richness', legacy: 'Raw Text Snippets', manual: 'Scattered Spreadsheets' },
      { feat: 'UX Recommendations', jurnii: '70+ Ranked Heuristics', legacy: 'Simple Funnel Dropout Counts', manual: 'High-Level Consultant Slideware' },
      { feat: 'Jurisdictional Coverage', jurnii: '35 Simultaneous Markets', legacy: 'Single Market / Restricted', manual: 'Local Only' },
    ],
  },
  cortex: {
    eyebrow: 'Cortex Attribution & Yield Impact',
    heading: 'Causal ROI Optimization',
    paras: [
      'All data harvested by Jurnii UX and Jurnii 360 is normalized and streamed directly into Cortex, our causal modeling and marketing mix attribution engine. Cortex eliminates last-click errors to attribute campaign success with statistical accuracy.',
      'By cataloging competitor promotions, pricing richness, and interface friction, Jurnii enables your data scientists to export MMM-ready datasets. Model the defensive strength of programmatic and search channels in real-time.',
    ],
    result: '+46% ROAS Lift',
    resultNote: 'Jurnii 360 tracks 100% of competitor promotion moves automatically, saving 30+ hours per week across CRM and commercial teams.',
  },
  testimonial: {
    quote: 'Before Jurnii, we calibrated our player onboarding bonuses and VIP tiers on subjective guesswork. Having normalized competitive feeds and causal attribution models shifted our growth playbook completely.',
    avatar: 'GM',
    name: 'General Manager, Europe iGaming Conglomerate',
    role: 'Integrated Portfolio Operations',
  },
  ecosystem: {
    heading: 'Intelligence Integrations',
    lede: 'Jurnii operates as a single unified system, feeding data seamlessly across your tech stack.',
    columns: [
      { label: 'Related Products', items: [
        { href: '/products/jurnii-ux', title: 'Jurnii UX', desc: 'Automated usability and visual scoring.' },
        { href: '/products/jurnii-mmm', title: 'Cortex', desc: 'Causal attribution and planning mix.' },
      ]},
      { label: 'Core Features', items: [
        { href: '/features/brand-usability', title: 'Usability', desc: 'Standardized heuristic usability auditing.' },
        { href: '/features/competitor-promotions', title: 'Promotions', desc: 'Automate promotional campaign tracking.' },
      ]},
      { label: 'Outcomes', items: [
        { href: '/solutions/user-experience-benchmarking', title: 'UX Benchmarking', desc: 'Heuristics-based experience index scores.' },
        { href: '/solutions/competition-offers', title: 'Competitor Intel', desc: 'Continuous surveillance of competitor campaigns.' },
      ]},
    ],
  },
};

// Metric presets reused across pages.
const M_ATTR = [
  { num: '+46%', label: 'True Marketing ROI Lift' },
  { num: '$4.85M', label: 'Budget Reallocated' },
  { num: '3×', label: 'Attribution Speed' },
  { num: '40×', label: 'ROI on Platform Investment' },
];
const M_360 = [
  { num: '1,000+', label: 'Offers Tracked Weekly' },
  { num: '35', label: 'Regulated Markets Monitored' },
  { num: '21', label: 'Feature Areas Scanned' },
  { num: '30+', label: 'Hours Saved per Week' },
];
const M_UX = [
  { num: '300+', label: 'Brands Analysed' },
  { num: '70+', label: 'Recommendations per Audit' },
  { num: '4', label: 'Key UX Dimensions' },
  { num: 'Mins', label: 'Time to Full Audit' },
];

window.USE_CASE_DATA = {
  // ---------------- ROLES ----------------
  cmo: {
    cat: 'roles', slug: 'cmo', icon: 'megaphone',
    label: 'CMO', cardTitle: 'Chief Marketing Officer',
    cardSummary: 'Kill last-click attribution leaks, isolate campaign incrementality, and align media-mix budgets with causal modeling.',
    kicker: 'Growth Attribution',
    title: 'Chief Marketing Officer',
    lede: 'Eliminate last-click attribution leaks, isolate campaign incrementality, and align media mix budgets with Jurnii 360 competitive intelligence and Cortex causal modeling.',
    metrics: M_ATTR,
    manifesto: 'Jurnii ingests competitor promotions and ad copy in real-time, giving Chief Marketing Officers the objective intelligence needed to maximize acquisition efficiency, defend market share, and justify marketing investment strategies to the board. By feeding real-time competitor promo data directly into Media Mix Modeling (MMM) frameworks, CMOs can transform raw competitive copy into predictive intelligence that powers ROAS.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'CMOs must defend market share and allocate budgets in highly competitive jurisdictions where player multi-homing rates reach 70–80%. Saturated paid search and programmatic channels lead to astronomical CPAs that erode campaign ROI. Relying on outdated, last-click attribution models masks the true causal impact of competitor promo shifts, causing marketers to chase ghost conversions while competitor wagering adjustments capture player loyalty silently.',
    solutionPara: 'Jurnii 360 tracks 100% of competitor moves automatically, cataloging over 1,000 active campaigns weekly. Cortex ingests competitor promotions data from Jurnii 360 across 21 feature areas and integrates them into causal models. This eliminates last-click attribution leaks and isolates the true incremental lift of programmatic and search spends against competitor actions across 35 markets monitored simultaneously.',
    solutionFoot: 'Chief Marketing Officers deploy Jurnii positioning maps and Cortex modeling to optimize media mix budgets and validate spend efficiency.',
    capabilities: [
      { icon: 'git-merge', title: 'Attribution Modelling', body: 'Isolate true incremental campaign yield and eliminate last-click attribution leaks by feeding competitor promotional data directly into causal Media Mix Modeling.' },
      { icon: 'palette', title: 'Creative Analytics', body: 'Monitor competitor banner messaging, active creative hooks, and positioning shifts instantly across 35 markets monitored simultaneously.' },
      { icon: 'layers', title: 'Promo Benchmarking', body: 'Analyze rival welcome bonus structures, sports odds boosts, and wagering hurdles systematically using the Promo Richness Index.' },
    ],
  },
  coo: {
    cat: 'roles', slug: 'coo', icon: 'briefcase',
    label: 'COO', cardTitle: 'Chief Operating Officer',
    cardSummary: 'Accelerate delivery cycles, remove onboarding friction, and align product and engineering around objective usability data.',
    kicker: 'Operational Excellence',
    title: 'Chief Operating Officer',
    lede: 'Accelerate product development cycles, eliminate player onboarding friction, and align cross-functional engineering and product pipelines with Jurnii UX automated scoring.',
    metrics: M_UX,
    manifesto: 'Operations leaders deploy Jurnii to align product, engineering, and marketing pipelines around objective usability indicators, eliminating manual competitive auditing and accelerating sprint impact. By establishing a single-source-of-truth usability database across scaling teams, COOs can bypass B2B vendor platform constraints and drive evidence-based development cycles that protect operator margins.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'Cross-functional hand-offs between product, marketing, and trading teams are slowed by opinion-driven disagreements and manual auditing workflows that waste 30+ hours per week. Operational friction compounds when operators enter new regulated markets or undergo platform migrations. Subtle interface drop-offs during KYC verification and deposit steps cause silent player abandonment that bleeds GGR, yet teams lack the structured metrics to prioritize the roadmap.',
    solutionPara: 'Jurnii UX runs automated, server-side heuristic audits across four key UX dimensions, producing 70+ commercially weighted recommendations per audit. Jurnii normalizes competitor registration processes and deposit requirements, delivering ranked usability heuristics that isolate actual funnel bottlenecks. This allows operations to replace subjective opinion with verified digital facts and guide development cycles by conversion yield impact.',
    solutionFoot: 'Chief Operating Officers deploy Jurnii automated surveillance to align technical pipelines and eliminate conversion latency.',
    capabilities: [
      { icon: 'workflow', title: 'Process Automation', body: 'Replace slow manual spreadsheet competitor audits with automated active data feeds and continuous heuristic scoring.' },
      { icon: 'filter', title: 'Friction Identification', body: 'Isolate and repair conversion leaks across high-value registration, document verification (KYC), and payment deposit pipelines.' },
      { icon: 'target', title: 'Sprint Alignment', body: 'Map developmental sprint roadmaps directly to verified industry usability standards, ranking updates by revenue impact.' },
    ],
  },
  cco: {
    cat: 'roles', slug: 'cco', icon: 'coins',
    label: 'CCO', cardTitle: 'Chief Commercial Officer',
    cardSummary: 'Protect EBITDA yields, calibrate promotional richness, and defend player lifetime value against margin dilution.',
    kicker: 'Margin Defence',
    title: 'Chief Commercial Officer',
    lede: 'Protect EBITDA yields, calibrate promotional richness, and defend player lifetime value by systematically identifying conversion path leaks.',
    metrics: M_360,
    manifesto: 'Commercial directors leverage Jurnii to protect yields, optimizing promotional richness and bonus wagering conditions based on continuous, automated market visibility. By bridging the gap between customer acquisition cost (CAC) and player lifetime value (LTV), Jurnii ensures commercial teams balance competitor positioning with strict margin preservation.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'CCOs are responsible for Net Gaming Revenue (NGR) and Gross Gaming Revenue (GGR), but player multi-homing rates of 70–80% make customer loyalty highly fragile. To prevent churn, CRM teams reactively deploy over-generous player bonuses, resulting in severe CRM margin dilution. Without live, automated competitor offer tracking, commercial analysts spend hours compiling competitor welcome offers, leaving the operator blind to the Promo Richness Index of the market.',
    solutionPara: "Jurnii 360's Promo Richness Index standardizes wagering rules and deposit incentives. This enables CCOs to calibrate margin thresholds, model competitor payout curves across verticals, and defend player lifetime value (LTV). Jurnii 360 tracks 100% of competitor promotion moves automatically, scraping over 1,000 active campaigns weekly to prevent margin erosion.",
    solutionFoot: 'Chief Commercial Officers leverage Jurnii promotions surveillance to balance customer acquisition generosity with strict yield safety.',
    capabilities: [
      { icon: 'trending-up', title: 'Yield Optimisation', body: 'Calibrate deposit matches and pricing richness against competitor bonus structures using the Promo Richness Index.' },
      { icon: 'heart', title: 'LTV Protection', body: 'Prevent player churn before it starts by monitoring rival retention plays, active casino campaigns, and sportsbook boosts in real-time.' },
      { icon: 'filter', title: 'Leak Remediation', body: 'Track and repair player progression leaks through high-value conversion funnels, registration steps, and withdrawal workflows.' },
    ],
  },

  // ---------------- COMPANY SIZES ----------------
  smb: {
    cat: 'company-sizes', slug: 'smb', icon: 'store',
    label: 'SMB', cardTitle: 'Small & Midsize Business',
    cardSummary: 'Scale acquisition and compete with conglomerates on localized market facts — without enterprise overheads.',
    kicker: 'Market Penetration',
    title: 'Small & Midsize Business',
    lede: 'Scale player acquisition, secure regional market share, and compete directly with global conglomerates without enterprise-level overheads.',
    metrics: M_ATTR,
    manifesto: 'Jurnii delivers rapid, high-impact intelligence tailored for emerging brands, allowing fast-scaling challenger operators to compete directly with global conglomerates by acting on precise, localized market facts. By providing immediate competitive tracking, Jurnii enables boutique operators to capture high-value market voids and lower acquisition CPA.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'Squeezed by massive operator conglomerates, fast-growing challengers spend limited budgets copying market generics. Without clear competitive context, they miss micro-campaign opportunities, experience high player leakage, and struggle with high CPAs. Manual competitive auditing is impossible at their scale, while hiring expensive consulting agencies to benchmark their experience takes weeks they cannot afford.',
    solutionPara: "Jurnii provides immediate, low-overhead competitor surveillance by tracking competitor welcome offers and usability states across target jurisdictions. Operators leverage Jurnii's global repository of 300+ brands analysed to identify welcome offer gaps, and deploy agile, highly targeted counter-campaigns that maximize every dollar spent on paid channels.",
    solutionFoot: "Scaling Founders and C-Suite leaders at SMB operators use Jurnii's out-of-the-box dashboards to maintain parity without enterprise-level overheads.",
    capabilities: [
      { icon: 'crosshair', title: 'Agile Positioning', body: 'Exploit local market gaps, welcome offer voids, and creative messaging opportunities left open by slower competitor conglomerates.' },
      { icon: 'wallet', title: 'Budget Efficiency', body: 'Maximize limited marketing budgets by analyzing and refining winning regional promotional frameworks and bonus wagering thresholds.' },
      { icon: 'zap', title: 'Fast Implementation', body: 'Access fully compiled competitor insights from day one, with zero complex database integrations or custom coding required.' },
    ],
  },
  midmarket: {
    cat: 'company-sizes', slug: 'midmarket', icon: 'building',
    label: 'Mid-Market', cardTitle: 'Mid-Market Operators',
    cardSummary: 'Secure expansion margins, defend home territory, and enter new regulated jurisdictions with full competitive visibility.',
    kicker: 'Scale & Expansion',
    title: 'Mid-Market Operators',
    lede: 'Secure expansion margins, defend home territory, and expand aggressively across new regulated jurisdictions with structured market intelligence.',
    metrics: M_360,
    manifesto: 'Mid-market operators utilize Jurnii to transition from regional player to national leader. By systematizing competitive tracking and aligning scaling executive teams around standardized indicators, growing operators can enter new jurisdictions with complete competitive visibility and locked-in acquisition margins.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'Scaling operators face high operational friction when entering new regulated markets (e.g., Ontario, Sweden, UK). Launching new brands or undergoing platform migrations creates immense UX drift and exposes player onboarding funnels to massive drop-offs. At this scale, teams become siloed; product managers ship features blindly without competitive context, while CRM teams copy rival promotions reactively.',
    solutionPara: "Jurnii automates competitor journey indexing and promotion scraping in target jurisdictions, supplying structured UX scores and promo tracking data to guide expansion. By calibrating UX against Jurnii's global repository of 300+ brands analysed across 4 key UX dimensions, mid-market operators prevent funnel leakage and secure expansion margins.",
    solutionFoot: "VP of Growth and Commercial Directors utilize Jurnii's regional maps to secure expansion margins and validate brand launches.",
    capabilities: [
      { icon: 'globe', title: 'Jurisdictional Expansion', body: 'Map player conversion loops, compliance terms, and local UX expectations across 35 markets monitored simultaneously.' },
      { icon: 'users', title: 'Organizational Alignment', body: 'Establish a single-source-of-truth usability database across growing marketing, commercial, and product departments.' },
      { icon: 'bar-chart-3', title: 'Attribution Scaling', body: 'Model campaign causal impacts and ROAS lift as marketing spend scales across diverse programmatic and search channels.' },
    ],
  },
  enterprise: {
    cat: 'company-sizes', slug: 'enterprise', icon: 'building-2',
    label: 'Enterprise', cardTitle: 'Enterprise Operators',
    cardSummary: 'Benchmark multi-brand portfolios, streamline global compliance, and unify intelligence across every jurisdiction.',
    kicker: 'Market Domination',
    title: 'Enterprise Operators',
    lede: 'Benchmark multi-brand portfolios, streamline global compliance, and dominate major jurisdictions with a unified commercial intelligence layer.',
    metrics: M_ATTR,
    manifesto: 'For top-tier multi-brand operators, Jurnii serves as the central intelligence layer. We harmonize UX scoring and competitor campaign scraping across complex, highly-regulated international markets, streaming normalized, structured API data directly into enterprise data warehouses to enable automated multi-brand scoring and causal budget optimization.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'Multi-brand, multi-jurisdiction conglomerates operate in data siloes where boards are flooded with subjective design feedback and manual reporting. Squeezed by player multi-homing rates of 70–80% across 35 regulated markets, teams struggle to track 1,000+ weekly competitor offers, leading to last-click attribution leaks and massive CRM margin dilution.',
    solutionPara: 'Jurnii streams structured, continuous competitor data directly into enterprise data warehouses. Cortex causal engines process multi-million dollar budgets to isolate campaign incrementality and true ROAS. Simultaneously, Jurnii UX automates usability audits across all portfolio brands, delivering 70+ commercially weighted recommendations ranked by conversion yield impact.',
    solutionFoot: 'Enterprise Chief Executive Officers and Boards leverage Jurnii Meta Scores to manage brand portfolios and defend global EBITDA.',
    capabilities: [
      { icon: 'layout-grid', title: 'Multi-Brand Benchmarking', body: 'Evaluate, rank, and grade your entire portfolio of brands side-by-side under a unified, commercially weighted metric system.' },
      { icon: 'shield-check', title: 'Regulatory Compliance', body: 'Maintain automated audit trails of competitor promotional terms, active welcome bonuses, and creative copy changes.' },
      { icon: 'database', title: 'Enterprise Data Pipes', body: 'Feed structured, continuous competitor promo and UX data directly into local MMM and analytics warehouses via robust APIs.' },
    ],
  },

  // ---------------- DEPARTMENTS ----------------
  marketing: {
    cat: 'departments', slug: 'marketing', icon: 'megaphone',
    label: 'Marketing', cardTitle: 'Marketing Department',
    cardSummary: 'Optimize campaigns on real-time competitor actions and defend budgets with causal media-mix attribution.',
    kicker: 'Growth Strategy',
    title: 'Marketing Department',
    lede: 'Eliminate subjectivity from marketing investments with the database, tracking, and attribution tools to optimize campaigns based on real-time competitor actions.',
    metrics: M_ATTR,
    manifesto: 'Eliminate subjectivity from marketing investments. Jurnii delivers the database, tracking, and attribution tools to optimize campaigns based on real-time competitor actions. By syncing continuous competitor promotional feeds with causal Media Mix Modeling, marketing teams can defend budgets and maximize acquisition efficiency.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'Marketing managers operate under blind CPA metrics. Last-click attribution fails to account for competitor sports boosts or casino wagering shifts, leading to bad budget allocations during peak sporting seasons. Saturated channels and player multi-homing rates of 70–80% make traditional marketing inefficient, while creative ad copywriting shifts go unnoticed.',
    solutionPara: 'Jurnii 360 parses and indexes competitor active banner creative, copy claims, and promo rich structures. This data is fed into Cortex to run causal modeling and marketing mix attribution, isolating the true incremental lift of programmatic and search spends against competitor actions across 35 markets monitored simultaneously.',
    solutionFoot: 'Acquisition Heads and Media Buyers use Jurnii campaign timelines to optimize ad spends and improve paid media ROAS.',
    capabilities: [
      { icon: 'radar', title: 'Campaign Scraping', body: 'Track all competitor welcome offers, deposit matches, and free spins dynamically as soon as they go live.' },
      { icon: 'image', title: 'Ad Creative Intel', body: 'Review competitor homepage banner placements, promotional sliders, and creative hooks across your competitive set.' },
      { icon: 'clock', title: 'Timing Optimization', body: 'Map historical competitor deployment patterns to schedule campaigns during peak commercial ROI windows.' },
    ],
  },
  commercial: {
    cat: 'departments', slug: 'commercial', icon: 'trending-up',
    label: 'Commercial', cardTitle: 'Commercial Department',
    cardSummary: 'Balance bonus incentives with net yield using standardized promo richness and payout-curve modeling.',
    kicker: 'Commercial Optimization',
    title: 'Commercial Department',
    lede: 'Bridge the gap between player acquisition costs and gaming yields with clear indices to evaluate pricing richness — without risking margin dilution.',
    metrics: M_360,
    manifesto: 'Commercial departments run on margins. Jurnii bridges the gap between player acquisition costs and gaming yields, supplying clear indices to evaluate pricing richness. By automating competitor offer tracking, commercial teams can optimize loyalty rewards without risking CRM margin dilution.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'Commercial teams struggle to balance player bonus incentives with net yield hold rates. Copying rival wagering thresholds by hand is slow, error-prone, and leads to margin erosion or sudden customer churn. Squeezed by player multi-homing rates of 70–80%, CRM teams duplicate rival promos reactively, causing severe margin dilution.',
    solutionPara: "Jurnii models competitor payout curves across sports and casino verticals. Jurnii 360's Promo Richness Index standardizes wagering rules and deposit incentives. This enables commercial analysts to calibrate margin thresholds, protect NGR from competitive dilution, and optimize player lifetime value (LTV) across 35 markets monitored simultaneously.",
    solutionFoot: 'Commercial Analysts and CRM Directors leverage Jurnii margin calibrators to deploy high-yield loyalty rewards.',
    capabilities: [
      { icon: 'layers', title: 'Promo Richness Index', body: 'Standardize the mathematical cost and yield margin impact of competitor deposit matches and retention bonuses.' },
      { icon: 'user-minus', title: 'Churn Analytics', body: 'Trace rival product changes and promotions causing high player leakage and multi-homing defection.' },
      { icon: 'search-check', title: 'Revenue Auditing', body: 'Identify conversion leaks and audits in affiliate reward structures, deposit funnels, and registration pathways.' },
    ],
  },
  product: {
    cat: 'departments', slug: 'product', icon: 'layout',
    label: 'Product', cardTitle: 'Product Department',
    cardSummary: 'Base sprints on objective heuristic rankings, not opinion — and build high-converting player journeys.',
    kicker: 'Product Excellence',
    title: 'Product Department',
    lede: 'Validate interface roadmaps and base development sprints on objective heuristic rankings rather than ad-hoc specifications or subjective opinions.',
    metrics: M_UX,
    manifesto: 'Product managers utilize Jurnii to validate interface roadmaps. Base development sprints on objective heuristic rankings rather than ad-hoc specifications or subjective opinions. By automating user experience audits, product teams can bypass B2B platform constraints and build high-converting player journeys.',
    challengeEyebrow: 'The Commercial Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'Product roadmaps are plagued by internal opinions. Usability reviews are slow and expensive, while B2B vendor platform constraints force product managers to ship features blindly without competitive context. Subtle interface drop-offs during KYC verification and deposit steps cause silent player abandonment that bleeds GGR, yet teams lack the structured metrics to prioritize the roadmap.',
    solutionPara: 'Jurnii UX delivers automated usability heuristics scoring across 4 key UX dimensions (registration, KYC verification, checkout, and account management). The platform generates 70+ commercially weighted recommendations per audit, ranking findings by revenue impact and allowing product teams to prioritize development cycles objectively.',
    solutionFoot: 'Chief Product Officers and Heads of UX deploy Jurnii heuristic scores to prioritize development cycles and outpace rival portals.',
    capabilities: [
      { icon: 'gauge', title: 'Heuristic UX Scoring', body: 'Automate user interface audits across core registration, verification, and deposit pipelines.' },
      { icon: 'route', title: 'Journey Mapping', body: 'Visualize player navigation pathways, visual UX scores, and friction points objectively.' },
      { icon: 'git-compare', title: 'Benchmark Auditing', body: 'Compare player journey speed and aesthetics side-by-side with 300+ global industry peers analysed.' },
    ],
  },

  // ---------------- SECTORS ----------------
  igaming: {
    cat: 'sectors', slug: 'igaming', icon: 'dices',
    label: 'iGaming', cardTitle: 'iGaming Operators',
    cardSummary: 'Native intelligence for sportsbooks, casinos, and lotteries — from onboarding UX to bonus scraping.',
    kicker: 'iGaming Excellence',
    title: 'iGaming Operators',
    lede: 'Real-time visibility into competitor player UX, deposit bonuses, and marketing attribution for sportsbooks, casinos, and lotteries.',
    metrics: M_360,
    manifesto: 'Jurnii is native to digital gaming, empowering sportsbooks, casinos, and lotteries with real-time visibility into competitor player UX, deposit bonuses, and marketing attribution. By analyzing competitor promotions and interface friction, Jurnii enables digital gaming operators to optimize net gaming yield and secure player conversions.',
    challengeEyebrow: 'The Sector Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'iGaming operators face extreme competition where player multi-homing rates reach 70–80% (players holding 3–5 competitor accounts simultaneously). Saturated marketing channels, rising CPAs, tight compliance rules, and commoditized B2B platforms make acquisition highly difficult. Subtle friction during registration, deposit, or KYC verification steps causes immediate abandonment to rivals, while manual promotional tracking is impossible to scale.',
    solutionPara: "Jurnii continuously monitors live casino and sportsbook onboarding pathways, tracking wagering hurdles and deposit multipliers dynamically. Jurnii 360's Promo Richness Index standardizes wagering rules across competitors, while Jurnii UX automates usability audits across registration, verification, and deposit funnels. This data feeds into Cortex for causal attribution, explaining ROAS lift against competitor movements.",
    solutionFoot: 'Chief Executive Officers at sportsbooks and casinos deploy Jurnii to secure player conversions and optimize net gaming yield.',
    capabilities: [
      { icon: 'dices', title: 'iGaming Heuristics', body: 'Track gaming registration, document verification (KYC), deposit, and betslip usability across 300+ brands analysed.' },
      { icon: 'gift', title: 'Bonus Scraping', body: 'Parse competitor sports boosts and casino promotions automatically as soon as they go live.' },
      { icon: 'scale', title: 'Compliance Tracking', body: 'Keep tabs on competitor promotional terms, active wagering multipliers, and layouts globally.' },
    ],
  },
  ecommerce: {
    cat: 'sectors', slug: 'ecommerce', icon: 'shopping-bag',
    label: 'eCommerce', cardTitle: 'eCommerce Brands',
    cardSummary: 'Map purchase journeys, cut cart abandonment, and benchmark promotional effectiveness against high-converting portals.',
    kicker: 'Conversion Scaling',
    title: 'eCommerce Brands',
    lede: 'Map player purchase journeys, identify cart abandonment causes, and benchmark promotional campaign effectiveness across high-volume digital brands.',
    metrics: M_UX,
    manifesto: 'High-volume digital brands utilize Jurnii to map player purchase journeys, identify cart abandonment causes, and benchmark promotional campaign effectiveness. By translating visual layout errors and cognitive fatigue into ranked heuristic recommendations, Jurnii ensures eCommerce operators maximize transaction yields and customer lifetime value.',
    challengeEyebrow: 'The Sector Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'eCommerce platforms suffer from severe cart abandonment at checkouts and payment gateway selections. Traditional analytics show where players drop off, but fail to explain the visual layout errors, confusing input validation messages, or pricing friction causing cognitive fatigue. Teams spend days debating design updates without objective data, while competitors adjust pricing and promotional codes dynamically.',
    solutionPara: 'Jurnii maps checkout grids, button placement, and copywriting clarity, benchmarking transaction states against leading high-converting digital portals. Jurnii UX audits security signals, payment gateways, and input validation to deliver commercially weighted recommendations that streamline checkout flows and increase purchase yields.',
    solutionFoot: 'Heads of eCommerce and Digital Merchandising utilize journey mapping to streamline multi-step checkouts and increase LTV.',
    capabilities: [
      { icon: 'shopping-cart', title: 'Checkout Optimization', body: 'Pinpoint interaction and UI friction causing cart abandonment in high-value purchase and checkout flows.' },
      { icon: 'tag', title: 'Price Benchmarking', body: 'Track competitor pricing, coupon codes, and loyalty perks in real-time across 35 markets monitored simultaneously.' },
      { icon: 'route', title: 'User Flow Mapping', body: 'Model cart additions, payment gateway selections, and multi-step checkouts objectively.' },
    ],
  },
  fintech: {
    cat: 'sectors', slug: 'fintech', icon: 'credit-card',
    label: 'FinTech', cardTitle: 'FinTech & Finance',
    cardSummary: 'Secure high-trust onboarding, audit KYC/AML friction, and design conversion-optimized banking interfaces.',
    kicker: 'Financial Platforms',
    title: 'FinTech & Finance',
    lede: 'Secure high-security customer registration, audit KYC and AML processing delays, and design conversion-optimized banking interfaces.',
    metrics: M_UX,
    manifesto: 'FinTech platforms leverage Jurnii to secure high-security customer registration, audit KYC and AML processing delays, and design conversion-optimized banking interfaces. By optimizing trust elements and mobile load speeds, Jurnii prevents registration funnel leakage and stabilizes acquisition costs.',
    challengeEyebrow: 'The Sector Challenge',
    challengeTitle: 'Operating Blind in a Saturated Market',
    challengePara: 'FinTech applications face extreme signup drop-offs during high-security AML, KYC, and document verification steps. Players lose trust when secure interfaces look generic, outdated, or confusing. Standard analytics tools cannot measure how layout security signals and compliance branding affect user confidence, leading to high abandonment rates and lost acquisition spends.',
    solutionPara: 'Jurnii audits security styling, compliance signals, and input validation messages across FinTech registration funnels. By comparing onboarding flows with industry best practices and 300+ analysed brands, Jurnii UX delivers commercially weighted improvements to ensure onboarding paths project maximum credibility, compliance, and safety.',
    solutionFoot: 'VP of Risk and Product Leads at FinTech platforms deploy Jurnii perception scores to secure compliance conversions.',
    capabilities: [
      { icon: 'shield-check', title: 'Onboarding Friction Audits', body: 'Optimize and accelerate high-security AML, KYC, and document upload pipelines.' },
      { icon: 'badge-check', title: 'Trust Elements Evaluation', body: 'Measure visual security indicators, compliance badges, and customer trust perception levels.' },
      { icon: 'smartphone', title: 'Mobile Performance Scoring', body: 'Ensure instant financial application loading and response speeds across mobile networks.' },
    ],
  },
};
