/**
 * GENERATED FILE — DO NOT EDIT BY HAND.
 *
 *   source:    zoho-functions/.agents/context/field_mapping/Jurnii Personas - Job Tile to Contact Role Mapping.csv
 *   generator: booking/scripts/job-titles-generate.js
 *   verify:    node booking/scripts/job-titles-generate.js --check
 *
 * The governed Job Title list offered by the booking form's autocomplete, derived from
 * the DISTINCT non-empty `Job_Title` values of the persona mapping CSV.
 *
 * It carries NO `Contact_Role` data. Title -> role mapping is owned by Zoho and
 * `processLead.deluge`; the browser neither knows nor submits a role.
 *
 * Not every title here is a valid `Leads.Job_Title` picklist value — the live picklist
 * is a curated subset. The server decides which of these may enter the governed
 * picklist and which travel as `Job_Title_Raw` only; see `governedTitle()` in
 * `booking/api/_utils/products.js`. The browser deliberately does not make that call.
 *
 * To change this list, edit the CSV and re-run the generator.
 */
(function (root, factory) {
  var api = factory();
  if (typeof module === 'object' && module.exports) module.exports = api;
  if (root) root.JurniiBookingJobTitles = api;
})(typeof globalThis !== 'undefined' ? globalThis : this, function () {
  'use strict';

  var TITLES = [
    "Account Executive",
    "Acquisition Manager",
    "Administrative Assistant",
    "Advanced Analytics Lead",
    "AI & Automation Lead",
    "AI Lead",
    "Analytics Engineer",
    "Art Director",
    "Associate Director of Product",
    "Attribution Manager",
    "Automation & AI Transformation Director",
    "Behavioural Analyst",
    "Betting Operations Manager",
    "BI Analyst",
    "BI Developer",
    "BI Manager",
    "Bonus Manager",
    "Brand & Marketing Director",
    "Brand & Product Marketing Lead",
    "Brand Manager",
    "Business Development Director",
    "Business Development Executive",
    "Business Operations Manager",
    "Campaign Manager",
    "Campaign Strategy Manager",
    "Casino Director",
    "Casino Manager",
    "Casino Product Manager",
    "Chief Architect",
    "Chief Assurance Officer",
    "Chief Commercial Officer",
    "Chief Customer Officer",
    "Chief Data Officer",
    "Chief Executive Officer",
    "Chief Financial Officer",
    "Chief Marketing Officer",
    "Chief of Staff",
    "Chief Online Gaming",
    "Chief Operating Officer",
    "Chief Product Officer",
    "Chief Revenue Officer",
    "Chief Strategy Officer",
    "Chief Systems Officer",
    "Chief Technology Officer",
    "Chief Trading Officer",
    "Chief Transformation Officer",
    "Client Director",
    "Client Partner",
    "Co-Founder",
    "Commercial Analyst",
    "Commercial Director",
    "Commercial Finance Manager",
    "Commercial Manager",
    "Commercial Planning Manager",
    "Commerical Director",
    "Company Director",
    "Competitor Intelligence Analyst",
    "Compliance Manager",
    "Compliance Product Manager",
    "Consultant",
    "Country Manager",
    "Creative Director",
    "Creative Lead",
    "CRM Director",
    "CRM Manager",
    "CRO Director",
    "CRO Manager",
    "CRO Product Manager",
    "Customer Excellence Department Head",
    "Customer Experience Director",
    "Customer Experience Insights Manager",
    "Customer Experience Manager",
    "Customer Insights Product Owner",
    "Customer Journey Manager",
    "Customer Operations Manager",
    "CX Manager",
    "Data Analyst",
    "Data Director",
    "Data Layer Specialist",
    "Data Visualisation Analyst",
    "Delivery Director",
    "Deputy Director",
    "Design Director",
    "Design Lead",
    "Design Manager",
    "Design Systems Engineer",
    "Design Systems Lead",
    "Designer",
    "Digital Analyst",
    "Digital Director",
    "Digital Experience Director",
    "Digital Product Manager",
    "Director",
    "Director & General Manager",
    "Director Customer Experience & Strategy",
    "Director of Applied Intelligence",
    "Director of Corporate Compliance",
    "Director of Corporate Security",
    "Director of CX & Optimisation",
    "Director of Digital Marketing",
    "Director of Digital Product",
    "Director of Engineering",
    "Director of Gaming",
    "Director of Generosity Transformation",
    "Director of Hospitality & General Services",
    "Director of Hotel Sales",
    "Director of Information Technology",
    "Director of Marketing",
    "Director of Marketing & Affiliation",
    "Director of Marketing Communications",
    "Director of Operations",
    "Director of Payments",
    "Director of People & Culture",
    "Director of Poker & Bingo",
    "Director of Poker Operations",
    "Director of Product",
    "Director of Product & Operations Management",
    "Director of Product Analysis",
    "Director of Product Compliance",
    "Director of Product Design",
    "Director of Product Development",
    "Director of Product Management",
    "Director of Product Operations",
    "Director of Project Management",
    "Director of Sportsbook",
    "Director of Strategy & Business Delivery",
    "Director of Strategy & Customer Experience",
    "Director of Technology",
    "Director of Trading Strategy",
    "Director of User Experience",
    "Director of UX & Growth",
    "Director Product & Tech",
    "Director Product & Technology",
    "Engineering Manager",
    "Experience Director (Product, CX, Data, Research & PMO)",
    "Experience Researcher",
    "Experimentation Lead",
    "Experimentation Manager",
    "Finance Business Partner",
    "Founder",
    "FP&A Director",
    "FP&A Manager",
    "Freelance Writer",
    "Frontend Developer",
    "Frontend Lead",
    "Gaming Director",
    "Gaming Product Manager",
    "General Manager",
    "Generosity Analytics & Segmentation Senior Manager",
    "Global CMO",
    "Global CXO",
    "Global Director of Product Support & Services",
    "Global Head of Product",
    "Global Product Director",
    "Global Product Manager",
    "Go-to-Market Manager",
    "Group CFO",
    "Group Chief Operating Officer",
    "Group Gaming Director EMEA",
    "Group Head of Commercial Gaming Operations",
    "Group Product Manager",
    "Group Strategy Director",
    "Group Trading Director",
    "Growth Director",
    "Head Cashier",
    "Head of Acquisition",
    "Head of Affiliates",
    "Head of AML",
    "Head of AML, Fraud & Risk",
    "Head of Analytics",
    "Head of B2B",
    "Head of Backend Engineering",
    "Head of BI",
    "Head of Brand",
    "Head of Brand & Creative",
    "Head of Brand Marketing",
    "Head of Business Development",
    "Head of Casino",
    "Head of Casino Business Development",
    "Head of Commercial",
    "Head of Compliance",
    "Head of Corporate Communications",
    "Head of Creative",
    "Head of Creative Research & Insights",
    "Head of CRM",
    "Head of CRO",
    "Head of Customer Care",
    "Head of Customer Excellence",
    "Head of Customer Experience",
    "Head of Customer Marketing",
    "Head of Customer Service",
    "Head of Customer Support",
    "Head of Customer Support & VIP Accounts Management",
    "Head of Customer Value Management",
    "Head of CX",
    "Head of Data Platform",
    "Head of Design",
    "Head of Digital",
    "Head of Digital Product",
    "Head of Engineering",
    "Head of Experience",
    "Head of Facility & Workplace Strategy",
    "Head of Finance",
    "Head of Gaming",
    "Head of Gaming Commercial",
    "Head of Gaming Operations",
    "Head of Gaming Product",
    "Head of Generosity Transformation",
    "Head of Greyhound Racing Operations",
    "Head of Group Marketing",
    "Head of Growth",
    "Head of Human Resources",
    "Head of iGaming",
    "Head of Infrastructure",
    "Head of Internal Audit",
    "Head of International Horse Racing",
    "Head of Investor Relations & Capital Deployment",
    "Head of Legal",
    "Head of Liquidity",
    "Head of Live Casino",
    "Head of Marketing",
    "Head of Online",
    "Head of Online & Customer Acquisition",
    "Head of Online Casino Operations",
    "Head of Operations",
    "Head of Operations & Support",
    "Head of Partnerships",
    "Head of People & Culture",
    "Head of Performance",
    "Head of Pricing Strategy & Insights",
    "Head of Product",
    "Head of Product Analytics",
    "Head of Product Design",
    "Head of Product Growth",
    "Head of Product Marketing",
    "Head of Program Product + Chief of Staff",
    "Head of Promotions",
    "Head of Proposition",
    "Head of Propositions",
    "Head of Research",
    "Head of Retention",
    "Head of Sales",
    "Head of SEO",
    "Head of Social",
    "Head of Special Product Development",
    "Head of Sports",
    "Head of Sportsbook",
    "Head of Strategy & Performance",
    "Head of Streaming Operations",
    "Head of Support Department",
    "Head of Technology",
    "Head of Trade Marketing",
    "Head of Trading",
    "Head of Trading & Risk",
    "Head of UX",
    "Head of UX & Design",
    "Head of VIP",
    "Head of VIP Services",
    "Head Trader",
    "Human Resources Business Partner",
    "Human Resources Director",
    "iGaming Product Manager",
    "Information & Product Analysis Specialist Manager",
    "Insight Manager",
    "Interaction Designer",
    "Lead Product Designer",
    "Legal Counsel",
    "Lifecycle Director",
    "Lifecycle Manager",
    "Lifecycle Marketing Manager",
    "Live Casino Manager",
    "Live Ops Product Manager",
    "Live Ops Product Manager, Head of Content",
    "M&A Principal",
    "Manager eGaming",
    "Manager of Global Product Management",
    "Manager Product Management",
    "Manager UX/UI & DA Gaming",
    "Managing Director",
    "Market Analyst",
    "Market Manager",
    "Marketing Analyst",
    "Marketing Director",
    "Marketing Manager",
    "Marketing Operations Manager",
    "OBG Strategy",
    "Offer Manager",
    "Operational Product Supplier Manager",
    "Optimisation Manager",
    "Owner",
    "Paid Search Executive",
    "Paid Search Manager",
    "Paid Social Manager",
    "Payment Product Manager",
    "Performance Marketing Director",
    "Performance Marketing Manager",
    "Planning & Execution Director",
    "Player Engagement Manager",
    "Player Experience Lead",
    "Player Operations Manager",
    "Player Protection Lead",
    "Player Value Manager",
    "Poker Product Manager",
    "President",
    "Pricing Analyst",
    "Pricing Strategy Director",
    "Principal Product Manager",
    "Product & Customer Support Manager",
    "Product & Design Operations Specialist",
    "Product & Experience Operations Manager",
    "Product & Insight Director",
    "Product Analyst",
    "Product Analytics",
    "Product Design Director",
    "Product Designer",
    "Product Director",
    "Product Experience Director",
    "Product Insights Manager",
    "Product Lead",
    "Product Management Lead",
    "Product Manager",
    "Product Manager & QA Lead",
    "Product Marketing Manager",
    "Product Operations Director",
    "Product Operations Manager",
    "Product Owner",
    "Product Release Manager",
    "Program Manager",
    "Promotions Director",
    "Promotions Manager",
    "Proposition Director",
    "Proposition Manager",
    "Regional Director",
    "Regional Head of Digital",
    "Regulatory Affairs Manager",
    "Research Manager",
    "Responsible Gambling Manager",
    "Retention Manager",
    "Revenue Director",
    "Safer Gambling Analyst",
    "Safer Gambling Lead",
    "Sales Manager",
    "Senior Business Development Manager",
    "Senior Commercial Manager",
    "Senior CRM Marketing Specialist",
    "Senior CVM Manager",
    "Senior Director Sportsbook Product",
    "Senior eCommerce Consultant",
    "Senior Generosity Transformation Manager",
    "Senior Global Brand Manager",
    "Senior Graphic Designer",
    "Senior IA & AI Business Transformation Architect",
    "Senior Legal & Regulatory Counsel",
    "Senior Manager",
    "Senior Manager New Business & Sales Executive",
    "Senior Product Designer",
    "Senior Product Development Manager",
    "Senior Product Manager",
    "Senior Product Owner",
    "Senior Project Leader",
    "Senior Research Manager",
    "Senior Sales Manager",
    "Senior UX Researcher",
    "Senior Vice President Product Development",
    "Sports Director",
    "Sportsbook Director",
    "Sportsbook Operations Manager",
    "Sportsbook Product Manager",
    "Sportsbook Property Director Kentucky",
    "Sportsbook Trading Manager",
    "Strategy Consultant",
    "Supplier Manager",
    "SVP Product",
    "Tagging Specialist",
    "Team Lead HR Business Partner",
    "Technical Director",
    "Tracking Specialist",
    "Trading Graduate",
    "Trading Manager",
    "UI Designer",
    "UK News Editor",
    "User Experience Research Manager",
    "User Research Lead",
    "User Research Manager",
    "User Researcher",
    "UX Analyst",
    "UX Architect",
    "UX Designer",
    "UX Director",
    "UX Researcher",
    "UX/UI Designer",
    "Vice Managing Director",
    "Vice President",
    "Vice President & General Manager",
    "Vice President Marketing",
    "Vice President of Commercials",
    "Vice President of Finance",
    "Vice President of Global Operations & Media",
    "Vice President of Human Resources",
    "Vice President of Operations",
    "Vice President of Pricing Strategy",
    "Vice President of Product",
    "Vice President of Product Development",
    "Vice President of Sales & Marketing",
    "Vice President Product Management",
    "Vice President Risk",
    "VIP Manager",
    "Voice of Customer Manager",
    "VP Customer Experience",
    "VP Growth",
    "VP Product",
    "Web Analyst",
    "Web Developer",
    "Website Manager",
    "Website Product Manager"
  ];

  return {
    TITLES: TITLES,
    /** Sentinel appended after the governed list; reveals the free-text field. */
    OTHER: "Other",
    SOURCE: "zoho-functions/.agents/context/field_mapping/Jurnii Personas - Job Tile to Contact Role Mapping.csv",
    SOURCE_SHA256: "ab43d6eae2f244a48be22c53c2dc03417338142fcfdd44314727d6fcd7ecf4c3"
  };
});
